<?php
/**
 * @author Maxim Cherednyk <maks757q@gmail.com, +380639960375>
 */

namespace maks757\eventsdata;


use maks757\language\entities\Language;
use yii\base\InvalidConfigException;
use yii\base\Module;
use yii\db\ActiveQuery;

class EventModule extends Module
{
    public $defaultRoute = 'post/index';
    public $multi_languages = true;
    public $language_class = null;
    public $language_default = null;
    public $language_where = null;
    public $language_field = null;
    /* @var  $model ActiveQuery */
    public $model;

    public function init()
    {
        if($this->multi_languages) {
            if (empty($this->language_class) && empty($this->language_field))
                throw new InvalidConfigException('Invalid params (\'language_class\' > className yor languages model) or (\'language_field\' > yor languages model field \'name language\' )');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

}